[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stock-market-research"
version = "0.1.0"
description = "A project for stock market research and report generation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pandas>=2.3.3",
    "yfinance>=0.2.66",
    "flask>=3.1.0",
    "requests>=2.32.5",
    "peewee>=3.18.2",
    "numpy>=2.3.3",
    "curl-cffi>=0.13.0",
    "notebook>=7.5.6"
]

[tool.setuptools]
py-modules = ["configuration", "create_report", "find_yahoo_id", "server"]

[tool.setuptools.packages.find]
where = ["."]
include = ["utils*"]
